### ISSUE TITLE
Add moment for selecting next day instead of the one applied. it should be in the format DD-MM-YYYY

### ISSUE THREAD

**Issue by TheNinza** [TheNinza/vaccimailer#10]
https://github.com/TheNinza/vaccimailer/blob/3d274eb4ce78953ffd7d04070c861fe41927432e/index.js#L45

**Comment by XDRAGON2002** [comment]
Can you elaborate a bit on the issue ?

**Comment by TheNinza** [comment]
hey @XDRAGON2002... Thanks for your interest.. but I think I should give others chance too for this issue...

**Comment by mounicasruthi** [comment]
I would like to work on this, can you please assign it to me? @TheNinza

**Comment by TheNinza** [comment]
sure @mounicasruthi , go ahead
