### ISSUE TITLE
Convert the barebones http implementation to express

### ISSUE THREAD

**Issue by TheNinza** [TheNinza/vaccimailer#3]

**Comment by harishfalco** [comment]
Hi theNinza , Can you provide more details about the issue and assign it to me? I am ready to work on this.

**Comment by TheNinza** [comment]
currently for creating the server, the app uses the http package from node (line 91). It should now use the express library for creating the server

**Comment by saif-malik-01** [comment]
@harishfalco I'm working on it.

**Comment by TheNinza** [comment]
sorry @saif-malik-01 , I can only assign one person for this. as @harishfalco was the first to comment, I have to assign this to him. I encourage you to look at other issues and more might come during hacktoberfest, so stay tuned.

**Comment by TheNinza** [comment]
Okay @harishfalco , go ahead!

**Comment by harishfalco** [comment]
Done
