### ISSUE TITLE
Change the got implementation to fetch vaccination details to axios

### ISSUE THREAD

**Issue by TheNinza** [TheNinza/vaccimailer#4]

**Comment by harishfalco** [comment]
Hi theNinza , Can you provide more details about the issue and assign it to me? I am ready to work on this.

**Comment by TheNinza** [comment]
currently closing this issue.. Will reopen on 1st october

**Comment by TheNinza** [comment]
Reopenning the issue.

**Comment by kailash360** [comment]
I want to work on this issue

**Comment by TheNinza** [comment]
Sure @kailash360 , go ahead

**Comment by kailash360** [comment]
I have created PR #8 for this issue @TheNinza
