### ISSUE TITLE
Create dynamic end points for the vaccination availability for different pincodes. (See description)

### ISSUE THREAD

**Issue by TheNinza** [TheNinza/vaccimailer#5]
1. http://localhost:PORT/subscribe?pincode=PINCODE&email=EMAIL should start listeners to listen for vaccination availability at the pincode PINCODE and send email at EMAIL

You might need to create some sort of global reference to different listeners for different pincodes and for those listeners.

eg:  
```js 
let listeners = {
    "pincode1" : {
        interval: intervalReference,    // to clear the interval in future if required
        emails:[email1, email2]
    },
    //pincode2: {...},
    //pincode3: {...}
}
```

(feel free to implement something different than this example)

2. http://localhost:PORT/unsubscribe?email=EMAIL should remove the email from receiving the email. Also clear the interval if no emails are associated with it.

3. http://localhost:PORT/all should return the all listeners and the emails associated with it

**Comment by XDRAGON2002** [comment]
Can you further elaborate on the issue ? Especially with reference to point 1

**Comment by TheNinza** [comment]
@XDRAGON2002 , Currently the pincode and the receiver's email address are hardcoded. I am looking for an endpoint which takes these two as query parameters and starts listening for availability of vaccine for that pincode and send email to the receiver when it is available. As depending on the url string, server will be having multiple email and pincode to respond and listen for vaccine availability. So there must be a way to listen for updates for multiple pincodes and respond to the emails which are querying for that pincode.

**Comment by TheNinza** [comment]
Tell me if you get the requirement, so that I can assign you this issue.

**Comment by XDRAGON2002** [comment]
@TheNinza Sure, I would like to work on this.

**Comment by TheNinza** [comment]
Sure go ahead

**Comment by XDRAGON2002** [comment]
@TheNinza I actually need to make a few changes to how the request is being made, as #4 has not been closed yet which replaces the current got implementation with axios, so I can only finish up this issue if that issue gets fixed, otherwise merge conflicts might occur. So waiting for that PR to be merged before making the final changes and submitting my own PR.
I have made all the needed endpoints and they all work as expected.

**Comment by TheNinza** [comment]
@XDRAGON2002  I just merged that PR.

**Comment by XDRAGON2002** [comment]
@TheNinza 
Opened PR #9 that fixes this issue.

**Comment by XDRAGON2002** [comment]
@TheNinza 
The PR #9 has been updated.

**Comment by XDRAGON2002** [comment]
@TheNinza 
Updated PR #9.
