### ISSUE TITLE
Add a user-friendly front-end

### ISSUE THREAD

**Issue by kailash360** [TheNinza/vaccimailer#7]
I would like to add a user-friendly frontend to the Node app, using HTML/CSS and JS.

**Comment by TheNinza** [comment]
@kailash360  are you thinking of frontend that displays the current JSON string in a better way (like some table)?

**Comment by kailash360** [comment]
I want to create 2 folders inside the current repository-Frontend and Backend. The backend will consist of current files, and I will add pages for frontend in HTML/CSS or React - as you suggest.

**Comment by TheNinza** [comment]
Okay I get the folder structure. I want to know what the frontend will provide to the user?

**Comment by kailash360** [comment]
It will consist of a form where the user can provide the email, password and other details, and then subscribe to the email service.

**Comment by TheNinza** [comment]
Our api currently not provides that functionality. That issue #5 is open. The frontend would be meaningless if the api is not there.

**Comment by TheNinza** [comment]
If you want to work on some other feature of frontend, I can suggest you this that you create a frontend for the '/' route which currently sends only the JSON string,  which will display that JSON in a nice way.

**Comment by kailash360** [comment]
Sir, can I start working on this now?

> If you want to work on some other feature of frontend, I can suggest you this that you create a frontend for the '/' route which currently sends only the JSON string, which will display that JSON in a nice way.

**Comment by TheNinza** [comment]
Yeahh @kailash360 , go ahead.. Sorry for the delay from my side.

**Comment by TheNinza** [comment]
Hey @kailash360 , can you update me on the status

**Comment by kailash360** [comment]
@TheNinza ,the frontend is ready. 
![image](https://user-images.githubusercontent.com/75155230/136270517-228d8d7c-e5b3-40e0-b733-8592d33f970d.png)
![image](https://user-images.githubusercontent.com/75155230/136270709-5f805c46-adf8-4e6b-9811-9f21a83a5b7e.png)


Please have a look and suggest changes, if any. 
Apologies for the delay. :)

**Comment by kailash360** [comment]
I have created the PR #18 for this issue.

**Comment by TheNinza** [comment]
hey @kailash360 , nice work, merging
